### ISSUE TITLE
Barnyard2 unable to see any events from snort's unified2 logs

### ISSUE THREAD

**Issue by ktran210** [firnsy/barnyard2#118]
I am completely stumped. Any help would be greatly appreciated:

Config: /etc/snort/snort.conf
output unified2: filename snort.log, limit 128

Config: /etc/snort/barnyard2.conf 
config hostname: localhost
config interface:  eth0
config waldo_file: /var/log/snort/barnyard2.waldo
config process_new_records_only
input unified2
output database: log, mysql, user=snorby password=<redacted> dbname=snorby host=localhost

To generate events in unified2 snort generated logs, I've added the following lines to local_rules
alert icmp any any -> any any (msg:"ICMP BadTest"; classtype:bad-unknown; sid:10000016; rev:1;)
alert tcp any any -> any any ( msg: "TCP Test1TCP detected!"; sid: 1; rev: 1;)

Started snort with this command:
# snort -i eth0 -u snort -g snort -c /etc/snort/snort.conf -l /var/log/snort/

Started barnyard2 with this command:
# barnyard2 -c /etc/snort/barnyard2.conf -f /var/log/snort/snort.log -w /var/log/snort/barnyard2.waldo -u snort -g snort -d /var/log/snort/ -v

The /var/log/snort/barnyard2.waldo has the right permission for snort user

When snort started,  unified2 log and alert files increases. I see lots of events
-rw-------  1 snort snort 404K Aug 21 17:23 snort.log.1408655695
-rw-r--r--  1 root  root  3.7M Aug 21 17:23 alert

File type for unified2 log:
[user]# file snort.log.1408654225
snort.log.1408654225: tcpdump capture file (little-endian) - version 2.4 (Ethernet, capture length 1514)

I'm able to open unified2 log with --> 'tcpdump -r snort.log.1408654225' which I presume is correct since it's a binary file that's output by snort?

When barnyard2 starts, it starts without any major errors:

```
    --== Initializing Barnyard2 ==--
```

Initializing Input Plugins!
Initializing Output Plugins!
Parsing config file "/etc/snort/barnyard2.conf"
## +[No entry in Signature Suppress List]+

+[ Signature Suppress list ]+

Barnyard2 spooler: Event cache size set to [2048]
Log directory = /var/log/snort
INFO database: Defaulting Reconnect/Transaction Error limit to 10
INFO database: Defaulting Reconnect sleep time to 5 second
Node unique name is: localhost:eth0

database: compiled support for (mysql)
database: configured to use mysql
database: schema version = 107
database:           host = localhost
database:           user = snorby
database:  database name = snorby
database:    sensor name = localhost:eth0
database:      sensor id = 1
database:     sensor cid = 5
database:  data encoding = hex
database:   detail level = full
database:     ignore_bpf = no
database: using the "log" facility

```
    --== Initialization Complete ==--
```

  ______   -_> Barnyard2 <_-
 / ,,_  \  Version 2.1.13 (Build 327)
 |o"  )~|  By Ian Firns (SecurixLive): http://www.securixlive.com/
- '''' +  (C) Copyright 2008-2013 Ian Firns firnsy@securixlive.com

Using waldo file '/var/log/snort/barnyard2.waldo':
    spool directory = /var/log/snort/
    spool filebase  = snort.log
    time_stamp      = 1408654225
    record_idx      = 0
Opened spool file '/var/log/snort//snort.log.1408654225'
Waiting for new data
Closing spool file '/var/log/snort//snort.log.1408654225'. Read 0 records
Opened spool file '/var/log/snort//snort.log.1408655695'
Waiting for new data

My problem is ---> Why are there no records read by Barnyard2?

I've done the following without any luck:
1) Restarted both snort and barnyard2 many times, in different order
2) Deleted all snort.log.\* files
3) Deleted barnyard2.waldo many times (and every time gave it the correct permission for 'snort'

What am I missing? I presume no records will be written to mysql until barnyard2 sees an event:
mysql> select \* from event;
Empty set (0.00 sec)

Thanks in advance for any help

KT

**Comment by ahamedfarzad** [comment]
Hi ktran210 ,

I have the same problem you had. I have changed /etc/sysconfig/snort file also. But I am still not getting unified2 log file. Any idea what I can do to fix this?

Thank you.

**Comment by sabrouna** [comment]
same problem please help

**Comment by wtfbbqhax** [comment]
@ktran210 

Can you clarify what lines you removed from what file please.

**Comment by juju19** [comment]
same problem, 
I have changed the  /etc/sysconfig/snort file too, uncomment ALERTMODE and BINARY_LOG
and this is my snort.conf setting
output unified2: filename merged.log, limit 128
the output filename still snort.log after I tried this page

Please help

**Comment by cadeath** [comment]
You can create a log file when you do -A console at snort, if you remove that, it will create a Unified2 file
you can verify it using `sudo u2spewfoo snort.u2.xxxxxxxxxxxxxx` command

Still my barnyard is not reading it and inserting it at the mySql...
It was working on testing, but not it is not...
