### ISSUE TITLE
snort generate logs ，barnyard2 can not read  records ？

### ISSUE THREAD

**Issue by dxb0719** [firnsy/barnyard2#127]
my snort version 2.9.6.2  barnyard2 -2.1.13
snort.conf :  output unified2: filename snort.log, limit 128

when i use "snort -A console -c /usr/local/snort/etc/snort.conf" command , snort can successfully generate logs  
-rw-------. 1 root root 229183 Nov 10 17:30 snort.log.1415611644
-rw-------. 1 root root  50982 Nov 10 17:30 snort.log.1415611812
-rw-------. 1 root root  34688 Nov 10 17:31 snort.log.1415611857

then i use "barnyard2 -c /usr/local/snort/etc/barnyard2.conf -d /var/log/snort -f snort.log" command , barnyard2 prompt to me ：
Waiting for new data
Closing spool file '/var/log/snort/snort.log.1415611644'. Read 0 records
Opened spool file '/var/log/snort/snort.log.1415611812'
Waiting for new data
Closing spool file '/var/log/snort/snort.log.1415611812'. Read 0 records
Opened spool file '/var/log/snort/snort.log.1415611857'

barnyard2 can not read record, then i use u2spewfoo tools ,see that ：
[snort]# u2spewfoo snort.log.1415611857
get_record: (3) Failed to read all of record data.
        Read 34680 of 33555456 bytes

i thought the snort log format is not correct ，so i change the configuration of snort.conf：
output log_unified2: filename snort.log, limit 128 

then barnyard2 prompt to me ：
WARNING database [Database()]: Called with Event[0x0] Event Type [0](P)acket [0x231d070], information has not been outputed. 
WARNING database [Database()]: Called with Event[0x0] Event Type [0](P)acket [0x231d070], information has not been outputed. 
WARNING database [Database()]: Called with Event[0x0] Event Type [0](P)acket [0x231d070], information has not been outputed. 

i have no idea ,any help?

**Comment by sabrouna** [comment]
Hi binf,same problem even i use unified2
help please

**Comment by binf** [comment]
Read the thread the answer is there.
