### ISSUE TITLE
dnet.h not found in barnyard2/src/

### ISSUE THREAD

**Issue by Natral** [firnsy/barnyard2#131]
not sure whats the problem... here is what i did...

$ ./autogen.sh
$ ./configure CFLAGS="-lpthread -g" --with-mysql --enable-prelude --with-mysql-libraries=/usr/lib/x86_64-linux-gnu --enable-ipv6 --prefix=$HOME/barnyard2-install
$ make

then got this error 

make[3]: Entering directory `/home/natral/barnyard2/src'
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -DSUP_IP6 -I/usr/include/mysql -DENABLE_MYSQL  -lpthread -g -fno-strict-aliasing -Wall -c decode.c
decode.c:38:18: fatal error: dnet.h: No such file or directory
compilation terminated.
make[3]: *** [decode.o] Error 1
make[3]: Leaving directory `/home/natral/barnyard2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/natral/barnyard2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/natral/barnyard2'
make: *** [all] Error 2

searched in git repository but didnt see any dnet.h file??? 
not sure what to do, would apreciate any assistance...

**Comment by Natral** [comment]
sorry... looked around and found the problem to be that i needed to install the dnet libraries from source so did the following

$ tar zxvf libdnet-1.12.tgz
$ cd libdnet-1.12/
$ ./configure CFLAGS=-fPIC; make
$ sudo checkinstall
$ sudo dpkg -i libdnet_1.12-1_amd64.deb
$ sudo ln -s /usr/local/lib/libdnet.1.0.1 /usr/lib/libdnet.1

this solved the problem for me... 
Thanks anyway for your time

**Comment by yehgdotnet** [comment]
http://macappstore.org/libdnet/

Press Command+Space and type Terminal and press enter/return key.
Run in Terminal app:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
and press enter/return key. Wait for the command to finish.
Run:
brew install libdnet
Done! You can now use libdnet.
