### ISSUE TITLE
daq.h NO such file or Directory.

### ISSUE THREAD

**Issue by Waseem-farooqui** [firnsy/barnyard2#133]
I am running Ubuntu 14.04.1 and trying to install barnyard2. I get this error when I run make.  I have tried every post suggestion and I am still at a loss.
**make**

  
![screenshot from 2015-02-16 130209](https://cloud.githubusercontent.com/assets/10846095/6208604/c6033a7e-b5dc-11e4-9369-722b5031b806.png)

**Comment by binf** [comment]
Make sure you installed libdaq from snort.org
wget https://www.snort.org/downloads/snort/daq-2.0.4.tar.gz

**Comment by Waseem-farooqui** [comment]
Thanks I test it via sudo there was a problem with its lib actually.Thanks

**Comment by sokoow** [comment]
Could you add a test against daq to configure/autotools script please ?
