### ISSUE TITLE
Startup script timeout (Centos 7)

### ISSUE THREAD

**Issue by Bubblejet** [firnsy/barnyard2#141]
Im running Centos 7 as a Snort IDS with Barnyard2/ Mysql with a Snorby GUI to view the alerts.

I am able to start Barnyard2 manually, but wanted to have it start automatically on server boot.

Barnyard comes with an /etc/init.d script which I copied over and attempted to run with
"service barnyard2 start"
from command line.

Resulting in the error message:
barnyard2.service operation timed out.

I will include the messages Im getting from journalctl -xn

The script is using the exact same startup arguments that I run manually, and it does seem to create the process daemon because I can run
"ps aux | grep barnyard2"
and see the pid, log into snorby and see the alerts being generated by snort etc, so barnyard2 seems to be working

If the daemon is being successfully spawned but Im getting a timeout message and the service is not being listed as started, is it simply the startup script? 
Ive never had to troubleshoot a startup script like this before.
Is there anything I can do to get further info on the timeout error?
I have posted on the Centos forums but no replies.

I am including the error message and the /etc/init.d script. Any help is greatly appreciated!
Thanks!

Below is the journalctl -xn messge received:
-- Logs begin at Mon 2015-03-09 23:35:56 EDT, end at Tue 2015-03-10 15:14:00 EDT. --
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: database: using the "log" facility
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: --== Initialization Complete ==--
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: Barnyard2 initialization completed successfully (pid=12477)
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: Using waldo file '/etc/snort/barnyard2-log.waldo': spool directory = /var/log/snort spool filebase = snort.log time_stamp = 1425973262 record_idx = 11
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: Opened spool file '/var/log/snort/snort.log.1425973262'
Mar 10 15:12:24 localhost.localdomain barnyard2[12477]: Waiting for new data
Mar 10 15:14:00 localhost.localdomain systemd[1]: barnyard2.service operation timed out. Terminating.
Mar 10 15:14:00 localhost.localdomain systemd[1]: Failed to start SYSV: Barnyard2 is an output processor for snort..
-- Subject: Unit barnyard2.service has failed -- Defined-By: systemd -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel[2] 
-- -- Unit barnyard2.service has failed. -- -- The result is failed.
Mar 10 15:14:00 localhost.localdomain systemd[1]: Unit barnyard2.service entered failed state.

Below is the (slightly modified) /etc/init.d script
 #!/bin/sh
 # Init file for Barnyard2
 # chkconfig: 2345 40 60 
 # description: Barnyard2 is an output processor for snort. 
 # processname: barnyard2 # config: /etc/sysconfig/barnyard2 
 # config: /etc/snort/barnyard.conf
 # pidfile: /var/lock/subsys/barnyard2.pid
source /etc/rc.d/init.d/functions 
source /etc/sysconfig/network
 ### Check that networking is up. [ "${NETWORKING}" == "no" ] && exit 0
[ -x /usr/sbin/snort ] || exit 1 [ -r /etc/snort/snort.conf ] || exit 1
 ### Default variables SYSCONFIG="/etc/sysconfig/barnyard2"
 ### Read configuration [ -r "$SYSCONFIG" ] && source "$SYSCONFIG"
RETVAL=0 
prog="barnyard2" 
desc="Snort Output Processor"
start() {
echo -n $"Starting $desc ($prog): "
for INT in $INTERFACES; do
WALDO_FILE="$SNORTDIR/$INT/barnyard2.waldo"
 BARNYARD_OPTS="-c /etc/snort/barnyard2.conf -d /var/log/barnyard2 -f snort.log -w /etc/snort/barnyard2-log.waldo -l /var/log/barnyard2 -a /var/log/barnyard2/archive -D"
daemon /usr/local/bin/barnyard2 $BARNYARD_OPTS
done
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
return $RETVAL
}
stop() {
echo -n $"Shutting down $desc ($prog): "
killproc $prog
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
return $RETVAL
}
restart() {
stop
start
}
reload() {
echo -n $"Reloading $desc ($prog): "
killproc $prog -HUP
RETVAL=$?
echo
return $RETVAL
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
reload)
reload
;;
condrestart)
[ -e /var/lock/subsys/$prog ] && restart
RETVAL=$?
;;
status)
status $prog
RETVAL=$?
;;
dump)
dump
;;
*)
echo $"Usage: $0 {start|stop|restart|reload|condrestart|status|dump}"
RETVAL=1
esac
exit $RETVAL

**Comment by JonPulsifer** [comment]
Here's a simple EL7 (systemd) service script I use on my sensor, it's not the best, but it does the job for me.

```sh
[Unit]
Description=Barnyard2 Dedicated Unified2 Spooler
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/barnyard2 -c /etc/barnyard2.conf -d /nsm/snort/ -f unified.log

[Install]
WantedBy=multi-user.target
```
Make something similar to that and throw it in a file named /etc/systemd/system/barnyard2.service and run the following commands:
```sh
systemctl enable barnyard2
systemctl start barnyard2
```

This should get you started, by no means is it a complete [or decent] solution, but it should put you on the right track.

Please, for your sanity, read this:
http://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by binf** [comment]
Didin't you read th reply on the mailing list?

**Comment by Bubblejet** [comment]
Switching to a systemctl script as suggested by JohnPulsifier seems to be working. 
I tried to do some troubleshooting on the init.d script but was never able to get it past the timeout.  
As Centos 7 is moving towards the systemctl route this is probably not a huge issue, though.
