### ISSUE TITLE
Compiling Error...

### ISSUE THREAD

**Issue by Tahajvm** [firnsy/barnyard2#149]
I am getting errors (some things about DAQ_PktHdr_t) compiling barnyard on ubuntu x86_64:
also i configure it with: ./configure --with-mysql --with-mysql-libraries=/usr/lib/x86_64-linux-gnu/ --with-mysql-includes=/usr/include/

make
make  all-recursive
make[1]: Entering directory `/usr/local/src/barnyard2'
Making all in src
make[2]: Entering directory `/usr/local/src/barnyard2/src'
Making all in sfutil
make[3]: Entering directory `/usr/local/src/barnyard2/src/sfutil'
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o getopt_long.o getopt_long.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sfmemcap.o sfmemcap.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sfprimetable.o sfprimetable.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sfxhash.o sfxhash.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sf_ip.o sf_ip.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sf_iph.o sf_iph.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sf_ipvar.o sf_ipvar.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sf_textlog.o sf_textlog.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o sf_vartable.o sf_vartable.c
rm -f libsfutil.a
ar cru libsfutil.a getopt_long.o sfmemcap.o sfprimetable.o sfxhash.o sf_ip.o sf_iph.o sf_ipvar.o sf_textlog.o sf_vartable.o
ranlib libsfutil.a
make[3]: Leaving directory `/usr/local/src/barnyard2/src/sfutil'
Making all in output-plugins
make[3]: Entering directory `/usr/local/src/barnyard2/src/output-plugins'
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_arubaaction.o spo_alert_arubaaction.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_bro.o spo_alert_bro.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_cef.o spo_alert_cef.c
spo_alert_cef.c: In function ‘AlertCEF’:
spo_alert_cef.c:500:15: warning: variable ‘cn’ set but not used [-Wunused-but-set-variable]
  ClassType   *cn;
               ^
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_csv.o spo_alert_csv.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_fast.o spo_alert_fast.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_full.o spo_alert_full.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_fwsam.o spo_alert_fwsam.c
spo_alert_fwsam.c: In function ‘AlertFWsam’:
spo_alert_fwsam.c:981:18: warning: variable ‘cn’ set but not used [-Wunused-but-set-variable]
     ClassType   *cn = NULL;
                  ^
spo_alert_fwsam.c:980:18: warning: variable ‘sn’ set but not used [-Wunused-but-set-variable]
     SigNode     *sn = NULL;
                  ^
spo_alert_fwsam.c:973:27: warning: variable ‘lastbsp’ set but not used [-Wunused-but-set-variable]
     static unsigned short lastbsp[FWSAM_REPET_BLOCKS];
                           ^
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_prelude.o spo_alert_prelude.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_syslog.o spo_alert_syslog.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_test.o spo_alert_test.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_alert_unixsock.o spo_alert_unixsock.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_common.o spo_common.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_log_ascii.o spo_log_ascii.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_log_null.o spo_log_null.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_log_tcpdump.o spo_log_tcpdump.c
spo_log_tcpdump.c: In function ‘LogTcpdumpSingle’:
spo_log_tcpdump.c:369:5: warning: passing argument 1 of ‘SizeOf’ from incompatible pointer type [enabled by default]
     size_t dumpSize = SizeOf(p->pkth);
     ^
spo_log_tcpdump.c:361:22: note: expected ‘const struct pcap_pkthdr *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 static INLINE size_t SizeOf (const struct pcap_pkthdr *pkth)
                      ^
spo_log_tcpdump.c:391:5: warning: passing argument 2 of ‘pcap_dump’ from incompatible pointer type [enabled by default]
     pcap_dump((u_char *)data->dumpd, p->pkth, p->pkt);
     ^
In file included from /usr/include/pcap.h:45:0,
                 from spo_log_tcpdump.c:55:
/usr/include/pcap/pcap.h:419:6: note: expected ‘const struct pcap_pkthdr *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void pcap_dump(u_char *, const struct pcap_pkthdr *, const u_char *);
      ^
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_sguil.o spo_sguil.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_echidna.o spo_echidna.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_syslog_full.o spo_syslog_full.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_database.o spo_database.c
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I ../sfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spo_database_cache.o spo_database_cache.c
rm -f libspo.a
ar cru libspo.a spo_alert_arubaaction.o spo_alert_bro.o spo_alert_cef.o spo_alert_csv.o spo_alert_fast.o spo_alert_full.o spo_alert_fwsam.o spo_alert_prelude.o spo_alert_syslog.o spo_alert_test.o spo_alert_unixsock.o spo_common.o spo_log_ascii.o spo_log_null.o spo_log_tcpdump.o spo_sguil.o spo_echidna.o spo_syslog_full.o spo_database.o spo_database_cache.o
ranlib libspo.a
make[3]: Leaving directory `/usr/local/src/barnyard2/src/output-plugins'
Making all in input-plugins
make[3]: Entering directory `/usr/local/src/barnyard2/src/input-plugins'
gcc -DHAVE_CONFIG_H -I. -I../..  -I.. -I../sfutil  -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spi_unified2.o spi_unified2.c
spi_unified2.c: In function ‘Unified2ReadRecord’:
spi_unified2.c:166:25: warning: variable ‘record_type’ set but not used [-Wunused-but-set-variable]
     uint32_t            record_type;
                         ^
rm -f libspi.a
ar cru libspi.a spi_unified2.o
ranlib libspi.a
make[3]: Leaving directory `/usr/local/src/barnyard2/src/input-plugins'
make[3]: Entering directory `/usr/local/src/barnyard2/src'
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o barnyard2.o barnyard2.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o debug.o debug.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o decode.o decode.c
decode.c:84:56: warning: ‘struct DAQ_PktHdr_t’ declared inside parameter list [enabled by default]
 int DecodePacket(int linktype, Packet *p, const struct DAQ_PktHdr_t *pkthdr, const uint8_t *pkt)
                                                        ^
decode.c:84:56: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
decode.c: In function ‘DecodePacket’:
decode.c:90:13: warning: passing argument 2 of ‘DecodeEthPkt’ from incompatible pointer type [enabled by default]
             DecodeEthPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1851:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeEthPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:95:13: warning: passing argument 2 of ‘DecodeIEEE80211Pkt’ from incompatible pointer type [enabled by default]
             DecodeIEEE80211Pkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1894:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeIEEE80211Pkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:100:13: warning: passing argument 2 of ‘DecodeEncPkt’ from incompatible pointer type [enabled by default]
             DecodeEncPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1903:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeEncPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:107:13: warning: passing argument 2 of ‘DecodeTRPkt’ from incompatible pointer type [enabled by default]
             DecodeTRPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1891:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeTRPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:111:13: warning: passing argument 2 of ‘DecodeFDDIPkt’ from incompatible pointer type [enabled by default]
             DecodeFDDIPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1892:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeFDDIPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:116:13: warning: passing argument 2 of ‘DecodeChdlcPkt’ from incompatible pointer type [enabled by default]
             DecodeChdlcPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1898:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeChdlcPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:128:13: warning: passing argument 2 of ‘DecodeSlipPkt’ from incompatible pointer type [enabled by default]
             DecodeSlipPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1895:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeSlipPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:141:13: warning: passing argument 2 of ‘DecodePppPkt’ from incompatible pointer type [enabled by default]
             DecodePppPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1901:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodePppPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:154:13: warning: passing argument 2 of ‘DecodePppSerialPkt’ from incompatible pointer type [enabled by default]
             DecodePppSerialPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1902:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodePppSerialPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:160:13: warning: passing argument 2 of ‘DecodeLinuxSLLPkt’ from incompatible pointer type [enabled by default]
             DecodeLinuxSLLPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1893:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeLinuxSLLPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:166:13: warning: passing argument 2 of ‘DecodePflog’ from incompatible pointer type [enabled by default]
             DecodePflog(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1899:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodePflog(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:189:13: warning: passing argument 2 of ‘DecodeNullPkt’ from incompatible pointer type [enabled by default]
             DecodeNullPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1852:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeNullPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
decode.c:206:13: warning: passing argument 2 of ‘DecodeRawPkt’ from incompatible pointer type [enabled by default]
             DecodeRawPkt(p, pkthdr, pkt);
             ^
In file included from decode.c:41:0:
decode.h:1853:6: note: expected ‘const struct DAQ_PktHdr_t *’ but argument is of type ‘const struct DAQ_PktHdr_t *’
 void DecodeRawPkt(Packet *, const DAQ_PktHdr_t*, const uint8_t *);
      ^
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o log.o log.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o log_text.o log_text.c
log_text.c: In function ‘LogTcpOptions’:
log_text.c:608:12: warning: variable ‘print_offset’ set but not used [-Wunused-but-set-variable]
     u_long print_offset;
            ^
log_text.c:607:12: warning: variable ‘init_offset’ set but not used [-Wunused-but-set-variable]
     u_long init_offset;
            ^
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o map.o map.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o mstring.o mstring.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o parser.o parser.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o plugbase.o plugbase.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o spooler.o spooler.c
spooler.c: In function ‘spoolerProcessRecord’:
spooler.c:740:9: warning: implicit declaration of function ‘DecodePacket’ [-Wimplicit-function-declaration]
         DecodePacket(datalink, spooler->record.pkt, &pkth,
         ^
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o strlcatu.o strlcatu.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o strlcpyu.o strlcpyu.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o twofish.o twofish.c
gcc -DHAVE_CONFIG_H -I. -I..  -Isfutil -I/usr/include//mysql -DENABLE_MYSQL  -g -O2 -fno-strict-aliasing -Wall -c -o util.o util.c
util.c: In function ‘GoDaemon’:
util.c:1091:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int ret = 0;
         ^
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -O2 -fno-strict-aliasing -Wall  -L/usr/lib/x86_64-linux-gnu/ -o barnyard2 barnyard2.o debug.o decode.o log.o log_text.o map.o mstring.o parser.o plugbase.o spooler.o strlcatu.o strlcpyu.o twofish.o util.o output-plugins/libspo.a input-plugins/libspi.a sfutil/libsfutil.a -lmysqlclient -lz -lpcap -lnsl -lm -lm
libtool: link: gcc -g -O2 -fno-strict-aliasing -Wall -o barnyard2 barnyard2.o debug.o decode.o log.o log_text.o map.o mstring.o parser.o plugbase.o spooler.o strlcatu.o strlcpyu.o twofish.o util.o  -L/usr/lib/x86_64-linux-gnu/ output-plugins/libspo.a input-plugins/libspi.a sfutil/libsfutil.a -lmysqlclient -lz -lpcap -lnsl -lm
make[3]: Leaving directory `/usr/local/src/barnyard2/src'
make[2]: Leaving directory `/usr/local/src/barnyard2/src'
Making all in etc
make[2]: Entering directory `/usr/local/src/barnyard2/etc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/src/barnyard2/etc'
Making all in doc
make[2]: Entering directory `/usr/local/src/barnyard2/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/src/barnyard2/doc'
Making all in rpm
make[2]: Entering directory `/usr/local/src/barnyard2/rpm'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/src/barnyard2/rpm'
Making all in schemas
make[2]: Entering directory `/usr/local/src/barnyard2/schemas'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/src/barnyard2/schemas'
Making all in m4
make[2]: Entering directory `/usr/local/src/barnyard2/m4'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/src/barnyard2/m4'
make[2]: Entering directory `/usr/local/src/barnyard2'
make[2]: Leaving directory `/usr/local/src/barnyard2'
make[1]: Leaving directory `/usr/local/src/barnyard2'

**Comment by Tahajvm** [comment]
barnyard version: 2.1.14 (Build 336)

after make install, barnyard installed without mysql support:
"ERROR database: 'mysql' support is not compiled into this build of barnyard2"

**Comment by Tahajvm** [comment]
Hi, Eric why u closed the thread?

**Comment by binf** [comment]
Make dist clean if you re-ran configure betwen compiles tries.
mysql support is working fine.
