### ISSUE TITLE
barnyard2 unable to process snort.conf

### ISSUE THREAD

**Issue by kirancse507** [firnsy/barnyard2#152]
Hi,

Snort version: Version 2.9.7.3 GRE (Build 217) 
OS: CentOS 7 (64-bit)

While styarting the barnyard2 I am getting the fatal error. it is unable to recognize ipvar variable.
I have changed all ipvar to var but then it is complaining about "ERROR: /etc/snort/snort.conf(123) Unknown config directive: disable_decode_alerts.".

Please see the full console log below.

Could you please help me with this issue? also, let me know how can I use ipvar with barnyard2.

/usr/local/bin/barnyard2 -c /etc/snort/snort.conf -d /var/log/snort -f snort.log -w /etc/snort/barnyard2-log.waldo -C /etc/snort/classification.config
Running in Continuous mode

        --== Initializing Barnyard2 ==--
Initializing Input Plugins!
Initializing Output Plugins!
Parsing config file "/etc/snort/snort.conf"
ERROR: /etc/snort/snort.conf(123) Unknown config directive: disable_decode_alerts.
Fatal Error, Quitting..
Barnyard2 exiting

**Comment by binf** [comment]
Barnyard2 need its own configuration file, it could be named snort.conf but
that could cause confusions.
By default barnyard2 will look for barnyard2.conf.

**Comment by kirancse507** [comment]
Thanks very much for the clarification. I have used the barnayrd.conf now.

But it seems like its ending after showing the below in console. I don't see any process running in background related to barnyard2. 

Please help if I am missing anything else..

Console output:

Running in Continuous mode

        --== Initializing Barnyard2 ==--
Initializing Input Plugins!
Initializing Output Plugins!
Parsing config file "/etc/snort/barnyard2.conf"

**Comment by binf** [comment]
What have you defined in your barnyard2.conf file?
Do you have unified2 file to process?

**Comment by kirancse507** [comment]
I don't have the unified2 file yet generated from snort. It seems I have issue with the snort itself. Let me work on that. Thanks again for the help.
