### ISSUE TITLE
barnyard2 is not writing events to the database in continuous mode

### ISSUE THREAD

**Issue by kirancse507** [firnsy/barnyard2#153]
Hi,

I am running barnayrd2, but it's not writing any events to the database.

Barnyard2 command:

/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf -d /var/log/snort -w /etc/snort/barnyard2-log.waldo -C /etc/snort/classification.config

I have also tried running batch mode. 

Command:

/usr/local/bin/barnyard2 -o -v -c /etc/snort/barnyard2.conf -d /var/log/snort -w /etc/snort/barnyard2-log.waldo -C /etc/snort/classification.config

I have run the u2spewfoo snort-unified2.log.1436096241 and it listed the events. I have copied at the bottom.

It looks like snort is producing the unfied2 logs but for some reason barnyard2 is unable to process them. Or there could be some problem with my configuration. Could you please help ?

Following is the console output after running barnyard2:

Barnyard2 spooler: Event cache size set to [2048] 
Log directory = /var/log/snort
INFO database: Defaulting Reconnect/Transaction Error limit to 10 
INFO database: Defaulting Reconnect sleep time to 5 second 
Node unique name is: Snort-Lab:enp0s8

+[ Signature Suppress list ]+
----------------------------
+[No entry in Signature Suppress List]+
----------------------------
+[ Signature Suppress list ]+

[SignatureReferencePullDataStore()]: No Reference found in database ... 
database: compiled support for (mysql)
database: configured to use mysql
database: schema version = 107
database:           host = localhost
database:           user = snort
database:  database name = snort
database:    sensor name = Snort-Lab:enp0s8
database:      sensor id = 2
database:     sensor cid = 3
database:  data encoding = hex
database:   detail level = full
database:     ignore_bpf = no
database: using the "log" facility

        --== Initialization Complete ==--

  ______   -*> Barnyard2 <*-
 / ,,_  \  Version 2.1.14 (Build 336)
 |o"  )~|  By Ian Firns (SecurixLive): http://www.securixlive.com/
 + '''' +  (C) Copyright 2008-2013 Ian Firns <firnsy@securixlive.com>

Using waldo file '/etc/snort/barnyard2-log.waldo':
    spool directory = /var/log/snort
    spool filebase  = snort.log
    time_stamp      = 1436069290
    record_idx      = 0
Waiting for new spool file

Console output from u2spewfoo :

(Event)
	sensor id: 0	event id: 8	event second: 1436099965	event microsecond: 499784
	sig id: 23	gen id: 122	revision: 1	 classification: 4
	priority: 2	ip source: 192.168.1.1	ip destination: 239.255.255.250
	src port: 0	dest port: 0	protocol: 17	impact_flag: 0	blocked: 0

Packet
	sensor id: 0	event id: 8	event second: 1436099965
	packet second: 1436099965	packet microsecond: 499784
	linktype: 1	packet_length: 182
[    0] 01 00 5E 7F FF FA 68 7F 74 E6 87 55 08 00 45 00  ..^...h.t..U..E.
[   16] 00 A8 12 4A 00 00 04 FF F1 90 C0 A8 01 01 EF FF  ...J............
[   32] FF FA 50 72 69 6F 72 69 74 79 20 43 6F 75 6E 74  ..Priority Count
[   48] 3A 20 30 0A 43 6F 6E 6E 65 63 74 69 6F 6E 20 43  : 0.Connection C
[   64] 6F 75 6E 74 3A 20 35 37 33 0A 49 50 20 43 6F 75  ount: 573.IP Cou
[   80] 6E 74 3A 20 33 0A 53 63 61 6E 6E 65 64 20 49 50  nt: 3.Scanned IP
[   96] 20 52 61 6E 67 65 3A 20 32 33 39 2E 32 35 35 2E   Range: 239.255.
[  112] 32 35 35 2E 32 35 30 3A 32 35 35 2E 32 35 35 2E  255.250:255.255.
[  128] 32 35 35 2E 32 35 35 0A 50 6F 72 74 2F 50 72 6F  255.255.Port/Pro
[  144] 74 6F 20 43 6F 75 6E 74 3A 20 33 0A 50 6F 72 74  to Count: 3.Port
[  160] 2F 50 72 6F 74 6F 20 52 61 6E 67 65 3A 20 36 38  /Proto Range: 68
[  176] 3A 31 39 30 30 0A                                :1900.

**Comment by binf** [comment]
Add -f snort-unified2.log to your barnyard2 command line.

**Comment by kirancse507** [comment]
I have tried -f as well. Here is the console output

/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf -d /var/log/snort -f /var/log/snort/snort-unified2.log -o -v -w /etc/snort/barnyard2-log.waldo -C /etc/snort/classification.config
Running in Continuous mode

        --== Initializing Barnyard2 ==--
Initializing Input Plugins!
Initializing Output Plugins!
Parsing config file "/etc/snort/barnyard2.conf"
INFO: Alerting on each packet associated with an event: is now enabled by default. 
 use: command line argument --disable-alert-on-each-packet-in-stream or 
 configure file argument disable-alert-on-each-packet-in-stream to disable the feature 


+[ Signature Suppress list ]+
----------------------------
+[No entry in Signature Suppress List]+
----------------------------
+[ Signature Suppress list ]+

Barnyard2 spooler: Event cache size set to [2048] 
Log directory = /var/log/snort
INFO database: Defaulting Reconnect/Transaction Error limit to 10 
INFO database: Defaulting Reconnect sleep time to 5 second 
Node unique name is: Snort-Lab:enp0s8

[SignatureReferencePullDataStore()]: No Reference found in database ... 
database: compiled support for (mysql)
database: configured to use mysql
database: schema version = 107
database:           host = localhost
database:           user = snort
database:  database name = snort
database:    sensor name = Snort-Lab:enp0s8
database:      sensor id = 2
database:     sensor cid = 3
database:  data encoding = hex
database:   detail level = full
database:     ignore_bpf = no
database: using the "log" facility

        --== Initialization Complete ==--

  ______   -*> Barnyard2 <*-
 / ,,_  \  Version 2.1.14 (Build 336)
 |o"  )~|  By Ian Firns (SecurixLive): http://www.securixlive.com/
 + '''' +  (C) Copyright 2008-2013 Ian Firns <firnsy@securixlive.com>

Using waldo file '/etc/snort/barnyard2-log.waldo':
    spool directory = /var/log/snort
    spool filebase  = snort.log
    time_stamp      = 1436069290
    record_idx      = 0
Waiting for new spool file

**Comment by kirancse507** [comment]
Hi,

I have run the batch mode correctly now and it processed the log file and has written the events to the database.

Command:

/usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf -v -o /var/log/snort/snort-unified2.log.1436096241 

Could you help me why is not working with continuous mode ?

Thanks,
Kiran

**Comment by kirancse507** [comment]
The correct usage for continues mode: /usr/local/bin/barnyard2 -c /etc/snort/barnyard2.conf -v -d /var/log/snort/ -f snort-unified2.log

its working now.
