### ISSUE TITLE
Barnyard2 does not read the output of snort - mysql empty

### ISSUE THREAD

**Issue by Tmolle** [firnsy/barnyard2#89]
Hello all,

Like many people, Barnyard2 does not read logs from Snort. But I don't understand why. Some help is welcome.

I use :  

```
Version 2.9.4 GRE (Build 40)
Barnyard2 - version 2-1.13
```

I test with only one local rule which is : 

```
alert icmp any any -> any any (msg: "test ICMP"; sid: 10000001;)
```

I tried with rev: 1; but it's not better.

When I run Snort, I can see the ICMP alerts.

```
#  snort -A console -q -u snort -g snort -c /etc/snort/snort.conf -i eth0
05/23-09:55:37.102206  [**] [1:10000001:1] test ICMP [**] [Priority: 0] {ICMP} 10.70.0.121 -> 10.70.0.178
05/23-09:55:37.102224  [**] [1:10000001:1] test ICMP [**] [Priority: 0] {ICMP} 10.70.0.178 -> 10.70.0.121
05/23-09:55:38.102885  [**] [1:10000001:1] test ICMP [**] [Priority: 0] {ICMP} 10.70.0.121 -> 10.70.0.178
```

And Barnyard2 is waiting for new data :

```
barnyard2 -c /etc/snort/barnyard2.conf -d /var/log/snort -f snort.log -w /var/log/snort/barnyard2.waldo
[...]
barnyard2: Closing spool file '/var/log/snort/snort.log.1369295582'. Read 0 records
barnyard2: Opened spool file '/var/log/snort/snort.log.1369295736'
barnyard2: Waiting for new data

ls -l /var/log/snort
-rw-------  1 snort snort    384 May 23 09:55 snort.log.1369295736
```

But my database is empty 

```
    mysql> select * from event;
    Empty set (0.00 sec)
```

Where

```
mysql> select * from sensor;
+-----+----------------+-----------+--------+--------+----------+----------+
| sid | hostname       | interface | filter | detail | encoding | last_cid |
+-----+----------------+-----------+--------+--------+----------+----------+
|   1 | localhost:eth0 | eth0      | NULL   |      1 |        0 |        0 |
+-----+----------------+-----------+--------+--------+----------+----------+
1 row in set (0.00 sec)
```

Below my config :

Snort : 

```
# unified2
# Recommended for most installs
output unified2: filename snort.log, limit 128
```

Barnyard2 : 

```
 output database: alert, mysql, user=snort password=******** dbname=snort host=localhost
```

Do you see a mistake somewhere?
Thanks in advance.

**Comment by Drewshg312** [comment]
Where can I find the answer??? There are only questions on this thread (as well as on any thread about snort...)

**Comment by purefan** [comment]
I really don't think this was solved by running snort in daemon mode (which [is what Tmolle did](https://github.com/firnsy/barnyard2/issues/89#issuecomment-18331920) when he said it "worked _better_" -> notice he **didn't say it fixes it**).

I have the same issue, snort is capturing packets and processing alerts, if I run 
`sudo snort -A console -q -u snort -g snort -c /etc/snort/snort.conf -i eth0`
I can see in console how it processes the rules for a simple ping (for testing purposes). 

I have been following [the official guide](https://snort.org/documents/snort-2-9-8-x-on-ubuntu-12-lts-and-14-lts-and-15) which does have [some _deviations_ that I was able to fix](http://purefan.me/barnyard2-and-sid-msg.map-warnings.html), the only hint that I can see now is that the waldo file is corrupted/truncated:

> WARNING: Ignoring corrupt/truncated waldofile '/var/log/snort/barnyard2.waldo'

My waldo file is empty (as per the instructions in that guide), and after changing permissions and ownerships to everything I could think of (snort and barnyard2 run as snort:snort and my waldo file is owned by snort:snort) I went to the source code, here's what I found:
- in the file [barnyard2.c](https://github.com/firnsy/barnyard2/blob/40b046d2d814ab6a75e218a10bc5272149362158/src/barnyard2.c) in line 350 that's where the warning is outputted:
  
`else if (ret == WALDO_FILE_ETRUNC)`
- `ret` is assigned in the same file by `ret = spoolerReadWaldo(&barnyard2_conf->waldo);`
- The function spoolerReadWaldo is in [spooler.c](https://github.com/firnsy/barnyard2/blob/40b046d2d814ab6a75e218a10bc5272149362158/src/spooler.c) starting in line 1154, and it returns WALDO_FILE_ETRUNC when `read` and `sizeof` are not equal (lines 1181 and 1184)

I understand the logic behind it as: _if the number of bytes that we read from the waldo file does not match the size of the WaldoData object then the file is corrupted or empty. _
But it fails, My understanding of the internals of barnyard2 is limited, but I guess the WaldoData object is not initialized to the contents of the waldo file. I have tried adding random data to the waldo file to discard just a return mismatch (`read` returning 0 and `sizeof` returning something else...) but it didn't help.

I suppose that to those whom this worked out of the box were maybe using a different build or followed a different set of instructions, but if someone is more familiar with barnyard2 please chip in, I strongly believe that running snort in daemon mode does not fix the issue of barnyard not reading snort logs
